* Becky Intro
Dr. Rebecca Bates is Professor of Computer Science and Chair of
Integrated Engineering at Minnesota State University, Mankato and was
a Fulbright Scholar at the University of Sao Paulo in Brazil.  Becky
teaches both Computer Science and Engineering.  Her classes are often
project-oriented with strong and explicit ties to broader social and
ethical themes.  My personal favorite fact is that Becky teaches an AI
and science fiction course.
* Becky Targeted Questions
+ Could you please just tell us about the sci fi and AI course first
  so I can geek out?
+ You lead a lot of project-based courses.  What do you think makes
  project-based learning successful for students?
+ Can you tell me about something you're a student of now, and what
  you learn from that experience as a teacher?
* Becky Question Pool
+ EVERY TIME: Describe a teacher you've had that you admired and what you admired about them.
+ Every time?: What's something you think every CSists should read, learn, do, or play with?

+ How do you establish the atmosphere of the course, where people are engaged, excited, and willing to take changes?
  + How do you fix the atmosphere in a course that's gone awry?
+ What's the most interesting non-CS teaching experience you've had? What did you learn from it?
  + What's something you're a student of now? What does your experience as a student tell you about teaching?
  + How have those experiences informed your teaching in CS?
+ How do you share your excitement about Computer Science with people outside the field?
+ What's your favorite computing story?
+ What's exciting to you in education that you have tried?
+ What's something we really don't need to know about CS anymore that's in our curricula?
+ How should CS reach out to the public?
** Secondary question pool
+ What's a course you wish you could teach?
+ What tips do you have for successfully teaching a large class (100+ people)?
+ What tips do you have for successfully teaching a small class (10- people)?
+ What's something cool you do in your teaching?
+ What do you do to prepare before a course starts?
+ How do you get to know your students?
+ How do you assess your students?
+ What do you do in lecture/class?
+ What's exciting that you haven't tried?
+ How do you identify and help students who are struggling?
+ How do you help students who are enthusiastic for extra work?
+ How do you keep a course fresh when you teach it multiple times?
+ How do you handle challenging students?
+ How do you manage TAs, both so that the basic needs of the course are met and so that those willing are inspired and able to go above and beyond?
+ How do you manage the classroom environment, particularly cell phones, laptops, and other distracting devices?
+ How do you get people to participate in class discussions?
+ How do you answer questions ("good" questions, "dumb" questions, etc.)?
+ What's something every Computer Scientist should know that's not in our curricula?
+ Tell us about something you tried in your teaching that went horribly awry.
+ Do you have topics where your own interest flags? What do you do?
+ What's something that students consistently have trouble learning in your courses? How do you address it?
+ What do you do for students who REALLY want some topic but your school just doesn't do it?
* Actual Questions
** Shout-outs
** Terminology
* TODO list for next time

